image: node:10.16.3
stages:
  - install
  - test
  - build
  - deploy

install-dep:
  stage: install
  script:
    - npm install --quiet
  artifacts:
    expire_in: 1hr
    paths:
      - node_modules/
  cache:
    paths:
      - node_modules/

test-app:
  stage: test
  variables:
    CHROME_BIN: google-chrome
  dependencies:
    - install-dep
  before_script:
    - apt update && apt install -yq apt-transport-https
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - sh -c 'echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - apt-get update && apt-get install -y google-chrome-stable
  script:
    - npm run test:ci
  only:
    - branches

build-app:
  stage: build
  variables:
    BUILD_CONFIGURATION: 'production'
  dependencies:
    - install-dep
  script:
    - npm run build-prod
  artifacts:
    expire_in: 1hr
    paths:
    - dist/

pages:
  stage: deploy
  dependencies:
    - build-app
  script:
    - mkdir public
    - mv ./dist/frontend/* ./public/
  artifacts:
    paths:
    - public
  environment:
    name: production
  only:
    - branches
